//
//  NewsDetailsWorkerTests.swift
//  NewsCleanSwift
//
//  Created by Vinita Miranda on 22/04/18.
//  Copyright (c) 2018 Vinita Miranda. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import NewsCleanSwift
import XCTest

class NewsDetailsWorkerTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: NewsDetailsWorker!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupNewsDetailsWorker()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupNewsDetailsWorker()
  {
    sut = NewsDetailsWorker()
  }
  
  // MARK: Test doubles
  
  // MARK: Tests

}
