//
//  NewsDetailsInteractorTests.swift
//  NewsCleanSwift
//
//  Created by Vinita Miranda on 22/04/18.
//  Copyright (c) 2018 Vinita Miranda. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import NewsCleanSwift
import XCTest

class NewsDetailsInteractorTests: XCTestCase {
  // MARK: Subject under test
  
  var sut: NewsDetailsInteractor!
  
  // MARK: Test lifecycle
  
  override func setUp() {
    super.setUp()
    setupNewsDetailsInteractor()
  }
  
  override func tearDown() {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupNewsDetailsInteractor() {
    sut = NewsDetailsInteractor()
  }
  
    
    class NewsDetailsPresentationLogicSpy: NewsDetailsPresentationLogic {
        var presentViewOnLoadCalled = false
        
        func presentViewOnLoad(_ response: NewsDetails.OnLoad.Response) {
            presentViewOnLoadCalled = true
        }
        
    }
    
    func testUpdateViewOnLoadShouldAskPresenterToPresentResponse() {
        // Given
        let newsDetailsPresentationLogicSpy = NewsDetailsPresentationLogicSpy()
        sut.presenter = newsDetailsPresentationLogicSpy
        
        // When
        let request = NewsDetails.OnLoad.Request()
        sut.article = Mock.News.articles[0]
        sut.updateViewOnLoad(request)
        
        // Then
        XCTAssert(newsDetailsPresentationLogicSpy.presentViewOnLoadCalled, "Update view on load should ask presenter to present response")
    }
    
}
