//
//  NewsDetailsPresenterTests.swift
//  NewsCleanSwift
//
//  Created by Vinita Miranda on 22/04/18.
//  Copyright (c) 2018 Vinita Miranda. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import NewsCleanSwift
import XCTest

class NewsDetailsPresenterTests: XCTestCase {
  // MARK: Subject under test
  
  var sut: NewsDetailsPresenter!
  
  // MARK: Test lifecycle
  
  override func setUp() {
    super.setUp()
    setupNewsDetailsPresenter()
  }
  
  override func tearDown() {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupNewsDetailsPresenter() {
    sut = NewsDetailsPresenter()
  }
  
    
    class NewsDetailsDisplayLogicSpy: NewsDetailsDisplayLogic {
        // MARK: Method call expectations
        
        var displayViewOnLoadCalled = false
        
        // MARK: Spied methods
        
        func displayViewOnLoad(viewModel: NewsDetails.OnLoad.ViewModel) {
            displayViewOnLoadCalled = true
        }
        
    }
    
    // MARK: Test doubles
    
    // MARK: Tests
    
    func testPresentViewOnLoadShouldDisplayViewOnLoad() {
        // Given
        let newsDetailsDisplayLogicSpy = NewsDetailsDisplayLogicSpy()
        sut.viewController = newsDetailsDisplayLogicSpy
        
        // When
        let response = NewsDetails.OnLoad.Response(url: "http://google.com/")
        sut.presentViewOnLoad(response)
        
        // Then
        XCTAssert(newsDetailsDisplayLogicSpy.displayViewOnLoadCalled, "Presenting view on load should display view on load")
    }
}
