# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewsCleanSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'Alamofire', '~> 4.7'
    pod 'SwiftyJSON'
    pod 'SDWebImage'
    pod 'SVProgressHUD'

  # Pods for NewsCleanSwift

  target 'NewsCleanSwiftTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'SwiftyJSON'


  end

  target 'NewsCleanSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
