//
//  NewsDetailsInteractor.swift
//  NewsCleanSwift
//
//  Created by Vinita Miranda on 18/04/18.
//  Copyright (c) 2018 Vinita Miranda. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewsDetailsBusinessLogic {
    func updateViewOnLoad(_ request: NewsDetails.OnLoad.Request)
}

protocol NewsDetailsDataStore {
    var article: Article! { get set }
}

class NewsDetailsInteractor: NewsDetailsDataStore {
    var article: Article!
    var presenter: NewsDetailsPresentationLogic?
    var worker: NewsDetailsWorker?
    
}

extension NewsDetailsInteractor: NewsDetailsBusinessLogic {
    func updateViewOnLoad(_ request: NewsDetails.OnLoad.Request) {
        presenter?.presentViewOnLoad(NewsDetails.OnLoad.Response(url: article.publishedAt))
    }
}
