//
//  NewsListingModels.swift
//  NewsCleanSwift
//
//  Created by Vinita Miranda on 15/04/18.
//  Copyright (c) 2018 Vinita Miranda. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum NewsListing {  
      enum Fetch {
        struct Request {
        }
        struct Response {
            var articles: [Article]!
        }
        struct Error {
            var error: NSError!
        }
        struct ViewModel {
            struct DisplayArticle {
                var sourceName : String!
                var displayAuthor: String!
                var displayTitle : String!
                var displayDetailedUrl : String!
                var displayIconUrl : String!
            }
            var displayArticles: [DisplayArticle]!
        }
      }
    
    enum Route {
        struct Request {
            var index: Int!
        }
        struct Response {
        }
        struct ViewModel {
        }
    }
}
