//
//  NewsListingRouter.swift
//  NewsCleanSwift
//
//  Created by Vinita Miranda on 15/04/18.
//  Copyright (c) 2018 Vinita Miranda. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewsListingRoutingLogic {
    func routeToNewsDetails()
}

protocol NewsListingDataPassing {
    var dataStore: NewsListingDataStore? { get }
}

class NewsListingRouter: NSObject, NewsListingRoutingLogic, NewsListingDataPassing {
    weak var viewController: NewsListingViewController?
    var dataStore: NewsListingDataStore?

    func routeToNewsDetails() {
        let destinationViewController = UIStoryboard(name: "Main", bundle: Bundle.main).instantiateViewController(withIdentifier: "NewsDetailsViewController") as! NewsDetailsViewController
        var destinationDS = destinationViewController.router!.dataStore!
        passDataToToNewsDetails(source: self.dataStore!, destination: &destinationDS)
        navigateToNewsDetails(source: viewController!, destination: destinationViewController)
    }
    
    func passDataToToNewsDetails(source: NewsListingDataStore, destination: inout NewsDetailsDataStore) {
        destination.article = source.selectedArticle
    }
    
    func navigateToNewsDetails(source: NewsListingViewController!, destination: NewsDetailsViewController) {
        source.navigationController?.show(destination, sender: nil)
    }

}
