//
//  NewsListingWorker.swift
//  NewsCleanSwift
//
//  Created by Vinita Miranda on 15/04/18.
//  Copyright (c) 2018 Vinita Miranda. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class NewsListingWorker {
    var newsListingStore: NewsListingProtocol

    init(newsListingStore: NewsListingProtocol) {
        self.newsListingStore = newsListingStore
    }
    
    func fetchNewsListing(_ request: NewsListing.Fetch.Request, completionHandler: @escaping (_ articles: [Article]?, _ error: NSError?) -> Void) {
        newsListingStore.fetchNewsListing(request) { (articles, error) in
            completionHandler(articles, error)
        }
    }
}


protocol NewsListingProtocol {
    func fetchNewsListing(_ request: NewsListing.Fetch.Request, completionHandler: @escaping (_ articles: [Article]?, _ error: NSError?) -> Void)
}
